version: "2"
linters:
  default: all
  disable:
    - copyloopvar
    - err113
    - godox
    - intrange
    - nlreturn
    - paralleltest
    - revive
    - testpackage
    - tparallel
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    cyclop:
      max-complexity: 15
    funlen:
      lines: 70
    gocognit:
      min-complexity: 40
    lll:
      line-length: 160
    gosec:
      excludes:
        - G204 # Subprocess launched with variable
        - G304 # Potential file inclusion via variable
    depguard:
      rules:
        regular:
          files:
            - !$test
          allow:
            - $gostd
            - github.com/michurin/human-readable-json-logging/slogtotext
            - github.com/Masterminds/sprig/v3
        tests:
          files:
            - $test
          allow:
            - $gostd
            - github.com/michurin/human-readable-json-logging/slogtotext
            - github.com/stretchr/testify
  exclusions:
    generated: lax
    warn-unused: true
    rules:
      - path: cmd/pplog/main.go
        linters:
          - dupword
          - errorlint
          - forbidigo
          - funlen
          - gochecknoglobals
          - gochecknoinits
          - mnd
      - path: slogtotext/example_slog_test.go
        linters:
          - exhaustruct
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/michurin/human-readable-json-logging)
