---
name: build # this string appears on badge
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: "Go ${{ matrix.go }} build and behavioral tests"
    strategy:
      matrix:
        go:
          - "1.18"
          - "1.19"
          - "1.20"
          - "1.21"
          - "1.22"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ matrix.go }}"
      - run: "go version"
      - run: "go build ./cmd/..."
      - run: "./behavioral-tests/run.sh"
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: "Unit test and lint"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - uses: golangci/golangci-lint-action@v6
        with:
          version: "v1.59"
      - run: "go test -v -race -coverprofile=coverage.txt -covermode=atomic ./..."
        env:
          GOEXPERIMENT: nocoverageredesign
      - uses: codecov/codecov-action@v4
        with:
          files: ./coverage.txt
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }} # required
