---
name: build # this string appears on badge
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: "Go ${{ matrix.go }} build and behavioral tests"
    strategy:
      matrix:
        go:
          - "1.18"
          - "1.19"
          - "1.20"
          - "1.21"
          - "1.22"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ matrix.go }}"
      - run: "go version"
      - run: "go build ./cmd/..."
      - run: "./behavioral-tests/run.sh"
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: "Unit test and lint"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - uses: golangci/golangci-lint-action@v3
        with:
          version: "v1.58"
      - run: "go test -v -race -coverprofile=coverage.txt -covermode=atomic ./..."
        env:
          GOEXPERIMENT: nocoverageredesign
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt
          verbose: true
defaults:
  run:
    # NOTE: some of behavioral-tests requires tty... but
    #
    # GitHub Actions run without a TTY device. This is a workaround to get one,
    # based on https://github.com/actions/runner/issues/241#issuecomment-2019042651
    shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"'
